.\" -*-nroff-*-
.TH EUREKA "6" "January 2015"
.SH NAME
Eureka \- a DOOM map editor
.SH SYNOPSIS
.B eureka
.RI "[" OPTION "...]"
.RI "[" FILE "...]"
.SH DESCRIPTION
Eureka is a cross-platform map editor for the classic DOOM games.

It features multiple-level undo and redo,
a 3D preview,
texture and thing browsers,
a built-in nodes builder,
panels for directly editing the properties of map objects,
a flexible key binding system,
and low system requirements (e.g. a 3D card is
.I not
required).
.SH OPTIONS
Note that long options are shown with two dashes, but may also be
used with a single dash for compatibility with DOOM ports.
.TP
.BI "\-f, \-file" " <file>..."
Wad file(s) to edit.
When no file is specified, Eureka will open the first map in the
IWAD (game wad).
.TP
.BI "\-w, \-warp" " <map>"
Level to edit.
This can be the full map name, e.g. "MAP12" or "E3M7",
but can also be a single number like "12" or "37",
or two separate numbers like "3 7" for compatibility with DOOM 1 and
Ultimate DOOM.
.TP
.BI "\-i, \-iwad" " <file>"
The name of the IWAD (game data).
This also determines which game the map is for, e.g. "doom.wad" will
mean the map is for DOOM 1, whereas "heretic.wad" will mean we are
editing for the game Heretic.
.TP
.BI "\-m, \-merge" " <file>..."
Resource file(s) to load
.TP
.BI "\-p, \-port" " <name>"
Port (engine) name.  The default port is "boom", but some other
supported ports are "vanilla" (the original EXE), "odamex", "edge"
and "legacy".
.TP
\fB\-h\fR   \fB\-help\fR
Show usage summary
.TP
\fB\-v\fR   \fB\-version\fR
Show version info
.TP
\fB\-d\fR   \fB\-debug\fR
Enable debugging messages
.TP
\fB\-q\fR   \fB\-quiet\fR
Quiet mode (no messages on stdout)
.SH CONFIGURATION
The following options blah...... FIXME
\fB\-home\fR
<dir>        Home directory
.TP
\fB\-install\fR
<dir>        Installation directory
.TP
\fB\-log\fR
<file>       Log messages to specified file
.TP
\fB\-config\fR
<file>       Config file to load / save
