.\" -*-nroff-*-
.TH EUREKA "6" "January 2015"
.SH NAME
Eureka \- a DOOM map editor
.SH SYNOPSIS
.B eureka
.RI "[" OPTION "...]"
.RI "[" FILE "...]"
.SH DESCRIPTION
Eureka is a cross-platform map editor for the classic DOOM games.

It features multiple-level undo and redo,
a 3D preview,
texture and thing browsers,
a built-in nodes builder,
panels for directly editing the properties of map objects,
a flexible key binding system,
and low system requirements (e.g. a 3D card is
.I not
required).
.SH OPTIONS
.TP
\fB\-h\fR   \fB\-help\fR
Show usage summary
.TP
\fB\-v\fR   \fB\-version\fR
Show version info
.TP
\fB\-d\fR   \fB\-debug\fR
Enable debugging messages
.TP
\fB\-q\fR   \fB\-quiet\fR
Quiet mode (no messages on stdout)
.TP
\fB\-home\fR
<dir>        Home directory
.TP
\fB\-install\fR
<dir>        Installation directory
.TP
\fB\-log\fR
<file>       Log messages to specified file
.TP
\fB\-config\fR
<file>       Config file to load / save
.TP
\fB\-i\fR   \fB\-iwad\fR
<file>       The name of the IWAD (game data)
.TP
\fB\-f\fR   \fB\-file\fR
<file>       Patch wad file to edit
.TP
\fB\-m\fR   \fB\-merge\fR
<file>...    Resource file(s) to load
.TP
\fB\-p\fR   \fB\-port\fR
<name>       Port (engine) name
.TP
\fB\-w\fR   \fB\-warp\fR
<map>        Select level to edit
