// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef __WINDOW_H__
#define __WINDOW_H__

#include <FL/Fl.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Progress.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Window.H>

class UI_MainWin : public Fl_Double_Window
{
public:
	// main settings

	Fl_Choice *game;
	Fl_Choice *mode;
	Fl_Choice *length;
	Fl_Value_Input *seed;
	Fl_Output *config;

	// user options

	Fl_Check_Button *big_mon;
	Fl_Check_Button *big_weap;
	Fl_Value_Input *macho;
	Fl_Value_Input *rooms;

	// bottom panel

	Fl_Button *about;
	Fl_Button *build;
	Fl_Button *quit;
	Fl_Progress *progress;

public:
	 UI_MainWin(const char *title);
	~UI_MainWin();
};

#endif  /* __WINDOW_H__ */

//--- editor settings ---
// vi:ts=4:sw=4:noexpandtab
