
/* initially generated by FLUID from silage.fl */

#include "window.h"

UI_MainWin::UI_MainWin(const char *title) :
  Fl_Double_Window(MAIN_WINDOW_W, MAIN_WINDOW_H, title)
{
	color((Fl_Color)18);
	callback((Fl_Callback*)load_res_callback);

	/* main settings */

	{	Fl_Group* o = new Fl_Group(0, 0, 260, 340);
		o->box(FL_FLAT_BOX);
		{ Fl_Box* o = new Fl_Box(10, 5, 195, 45, "Main Settings");
			o->labelfont(1);
			o->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
		}
		{ game = new Fl_Choice(80, 50, 120, 25, "Game:");
			game->down_box(FL_BORDER_BOX);
			game->callback((Fl_Callback*)iwad_callback);
		}
		{ mode = new Fl_Choice(80, 95, 120, 25, "Mode:");
			mode->down_box(FL_BORDER_BOX);
			mode->callback((Fl_Callback*)port_callback);
		}
		{ length = new Fl_Choice(80, 135, 120, 25, "Length:");
			length->down_box(FL_BORDER_BOX);
			length->callback((Fl_Callback*)port_callback);
		}
		{ seed = new Fl_Value_Input(75, 245, 85, 30, "Seed:");
		}
		{ Fl_Button* o = new Fl_Button(170, 245, 30, 30, "-");
			o->labelsize(20);
			o->callback((Fl_Callback*)kill_callback);
		}
		{ Fl_Button* o = new Fl_Button(210, 245, 30, 30, "+");
			o->labelsize(20);
			o->callback((Fl_Callback*)kill_callback);
		}
		{ config = new Fl_Output(75, 195, 105, 30, "Config:");
		}
		{ Fl_Button* o = new Fl_Button(190, 195, 55, 30, "Load");
			o->labelsize(12);
		}
		o->end();
	}

	/* user options */

	{	Fl_Group* o = new Fl_Group(265, 0, 260, 340);
		o->box(FL_FLAT_BOX);
		{ Fl_Box* o = new Fl_Box(275, 8, 160, 34, "Playing Options");
			o->labelfont(1);
			o->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
		}
		{ big_mon = new Fl_Check_Button(305, 50, 180, 30, " Big monsters");
			big_mon->down_box(FL_DOWN_BOX);
		}
		{ big_weap = new Fl_Check_Button(305, 90, 180, 30, " Big weapons");
			big_weap->down_box(FL_DOWN_BOX);
		}
		{ macho = new Fl_Value_Input(340, 195, 80, 30, "Macho:");
		}
		{ Fl_Button* o = new Fl_Button(430, 195, 30, 30, "-");
			o->labelsize(20);
		}
		{ Fl_Button* o = new Fl_Button(470, 195, 30, 30, "+");
			o->labelsize(20);
		}
		{ rooms = new Fl_Value_Input(340, 245, 80, 30, "Rooms:");
		}
		{ Fl_Button* o = new Fl_Button(430, 245, 30, 30, "-");
			o->labelsize(20);
			o->callback((Fl_Callback*)kill_callback);
		}
		{ Fl_Button* o = new Fl_Button(470, 245, 30, 30, "+");
			o->labelsize(20);
			o->callback((Fl_Callback*)kill_callback);
		}
		o->end();
	}

	/* bottom panel */

	about = new Fl_Button(220, 355, 80, 36, "About");
	about->labelsize(16);
	about->callback((Fl_Callback*)close_callback);

	build = new Fl_Button(325, 355, 80, 36, "Build");
	build->labelfont(1);
	build->labelsize(16);
	build->callback((Fl_Callback*)apply_callback);

	quit = new Fl_Button(430, 355, 75, 36, "Quit");
	quit->labelsize(16);
	quit->callback((Fl_Callback*)close_callback);

	progress = new Fl_Progress(10, 354, 185, 36, "Ready!");

	end();
}

//--- editor settings ---
// vi:ts=4:sw=4:noexpandtab
