name: Build for macOS

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  #
  # Nightly build helper
  # https://stackoverflow.com/a/67527144
  # https://docs.github.com/en/actions/use-cases-and-examples/deploying/installing-an-apple-certificate-on-macos-runners-for-xcode-development
  # https://github.com/marketplace/actions/code-sign-action
  # https://github.com/marketplace/actions/codesign-and-notarize
  #
  build-with-signing:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.MACOS_BUILD_CERTIFICATE_BASE64}}
          P12_PASSWORD: ${{ secrets.MACOS_P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.MACOS_KEYCHAIN_PASSWORD }}
        run: |
          # Create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o "$CERTIFICATE_PATH"
          
          # Create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"

          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k "$KEYCHAIN_PATH"
          security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security list-keychain -d user -s $KEYCHAIN_PATH
      - name: Generate project
        run: cmake -B build
      - name: Build
        run: |
          cmake --build build --config Release --parallel
          ls -al
          echo "CURDIR"
          pwd
          echo "BUILD DIR"
          ls -al build
      # TODO: install app store connect API key (see the apple-code-signing link above)
      - name: Sign and notarize the bundle
        uses: toitlang/action-macos-sign-notarize@v1.2.0
        with:
          certificate: ${{ secrets.MACOS_BUILD_CERTIFICATE_BASE64 }}
          certificate-password: ${{ secrets.MACOS_P12_PASSWORD }}
          username: ${{ secrets.MACOS_NOTARY_USER }}
          password: ${{ secrets.MACOS_NOTARY_PASSWORD }}
          apple-team-id: ${{ secrets.MACOS_TEAM_ID }}
          app-path: build/Eureka Doom Editor.app
      # TODO: test
      # TODO: archive
      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: EurekaEditor-macOS
          path: build/Eureka Doom Editor.app
