name: Build for macOS

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  #
  # Nightly build helper
  # https://stackoverflow.com/a/67527144
  # https://docs.github.com/en/actions/use-cases-and-examples/deploying/installing-an-apple-certificate-on-macos-runners-for-xcode-development
  # https://github.com/marketplace/actions/code-sign-action
  # https://github.com/marketplace/actions/codesign-and-notarize
  #
  build-with-signing:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate project
        run: cmake -B build
      - name: Build
        run: |
          cmake --build build --config Release --parallel
          ls -al
          echo "CURDIR"
          pwd
          echo "BUILD DIR"
          ls -al build
      # TODO: install app store connect API key (see the apple-code-signing link above)
      - name: Sign and notarize the bundle
        uses: ioan-chera/action-macos-sign-notarize@v1.3
        with:
          certificate: ${{ secrets.MACOS_BUILD_CERTIFICATE_BASE64 }}
          certificate-password: ${{ secrets.MACOS_P12_PASSWORD }}
          username: ${{ secrets.MACOS_NOTARY_USER }}
          password: ${{ secrets.MACOS_NOTARY_PASSWORD }}
          entitlements-path: osx/EurekaApp/eureka.entitlements
          apple-team-id: ${{ secrets.MACOS_TEAM_ID }}
          app-path: build/Eureka Doom Editor.app
      # TODO: test
      # TODO: archive
      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: EurekaEditor-macOS
          path: build/Eureka Doom Editor.app
